# -*- coding: utf-8 -*-
"""board.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uPJ_xtwXwGqzyP203y7FKcAA-N57Ut_x
"""

board = [["-", "-", "-"], ["-", "-", "-"], ["-","-","-"]]

def print_board():
  for ele in board:
    print(ele)

def check_mark(row, col):
  pass

def place_mark(row, col, player):
  pass

def check_win(player):
  pass

def main():
  print('Hello!')
  print_board()
main()